apiVersion: v1
kind: Secret
metadata:
  name: metrics-reader
  namespace: system
  annotations:
    kubernetes.io/service-account.name: notification-controller-metrics-reader
type: kubernetes.io/service-account-token
