---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konflux-ci.com
  resources:
  - notificationservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konflux-ci.com
  resources:
  - notificationservices/finalizers
  verbs:
  - update
- apiGroups:
  - konflux-ci.com
  resources:
  - notificationservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/finalizers
  verbs:
  - update
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update